# Programs
CROSSMAP: ../software/CrossMap-0.2.7/bin/CrossMap.py
bigWigToBedGraph: /programs/ucsc/userApps/bin/bigWigToBedGraph
METILENE: ../software/metilene_v0.2-7/metilene_linux64
BISMARK-METH-EXTRACT: ../software/Bismark-0.20.0/bismark_methylation_extractor

#references
hg38tohg19: ../references/hg38ToHg19.over.chain.gz
HG19: ../references/hg19_bwameth/hg19.fa
HG19_CHR_LENGTHS: ../references/hg19.chr.lengths
#Strings
AUTOSOMALCHROMO: chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22
